#!/bin/bash
T=`mktemp -d`

cd stro4k/src
nasm -f elf64 -d NUM_THREADS=$2 -d TT_SIZE_MB=$3 combined.asm -o $T/combined.o
cd ../..

pushd $T
ld.lld combined.o -o STRO4K --static -O3 --gc-sections --print-gc-sections -m "elf_x86_64" --as-needed --omagic

git clone https://github.com/aunali1/super-strip
cd super-strip
make
cd ..

./super-strip/sstrip -z STRO4K
xz -ze9fF raw -S .xz --x86 --lzma2 STRO4K
popd

cat unpack.sh $T/STRO4K.xz > $1
chmod +x $1

rm -rf $T
